// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddHistory(arg1:main.HistoryEntry):Promise<void>;

export function CancelRequest():Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteKV(arg1:string):Promise<void>;

export function GetKV(arg1:string):Promise<string>;

export function LoadCollections():Promise<Array<main.CollectionNode>>;

export function LoadEnvironments():Promise<Array<main.Environment>>;

export function LoadHistory(arg1:number):Promise<Array<main.HistoryEntry>>;

export function SaveCollections(arg1:Array<main.CollectionNode>):Promise<void>;

export function SaveEnvironments(arg1:Array<main.Environment>):Promise<void>;

export function SendRequest(arg1:main.HTTPRequest):Promise<main.HTTPResponse>;

export function SetKV(arg1:string,arg2:string):Promise<void>;
