// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function CancelRequest() {
  return window['go']['main']['App']['CancelRequest']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteKV(arg1) {
  return window['go']['main']['App']['DeleteKV'](arg1);
}

export function GetKV(arg1) {
  return window['go']['main']['App']['GetKV'](arg1);
}

export function LoadCollections() {
  return window['go']['main']['App']['LoadCollections']();
}

export function LoadEnvironments() {
  return window['go']['main']['App']['LoadEnvironments']();
}

export function LoadHistory(arg1) {
  return window['go']['main']['App']['LoadHistory'](arg1);
}

export function SaveCollections(arg1) {
  return window['go']['main']['App']['SaveCollections'](arg1);
}

export function SaveEnvironments(arg1) {
  return window['go']['main']['App']['SaveEnvironments'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetKV(arg1, arg2) {
  return window['go']['main']['App']['SetKV'](arg1, arg2);
}
